### ISSUE TITLE
ghurlbot does not set assignee nor 'action' label for "action issues" it creates

### ISSUE THREAD

**Issue by pchampin** [w3c/GHURLBot#3]
I have done [some experiments] with creating actions with ghurlbot for the rdf-star WG, but contrarily to [what the doc says]:

* ghurlbot does *not* add the `action` label to the issue it creates
* ghurlbot does *not* assign the issue to the user named on IRC

This might have to do with the fact that, when I first told ghurlbot to use the w3c/rdf-star-wg repo, this repo did not have an `action` label, and I (pchampin) was not in the contributors list of the repo. But this is now fixed, and the problem is still there...

[some experiments]: https://github.com/w3c/rdf-star-wg/issues?q=is%3Aissue+ghurlbot
[what the doc says]: https://w3c.github.io/GHURLBot/manual.html#create-actio

**Comment by bert-github** [comment]
I now think it is because ghurlbot didn't have sufficient access rights on the repository. The [GitHub documentation](https://docs.github.com/en/rest/issues/issues?apiVersion=2022-11-28#create-an-issue) says that, in that case, labels and assignees are silently dropped from a request to create an issue, even though the issue itself is created and the server returns a 201 response.

I've now given ghurlbot write access to rdf-star-wg. Too late for today's meeting, but maybe you can try next time.

**Comment by pchampin** [comment]
Awesome, thanks :)
Ideally, ghurlbot should check whether everything went well, and issue a warning if it detects that it does not have sufficient permissions...
Or at least, add this as an FAQ in the ghurlbot documentation. Other people might run into that problem.

**Comment by bert-github** [comment]
I have now added it to the manual, although it is not very prominent. I'll see if I should add an FAQ.

But the bot will now also print a warning if the created action does not have a label or if not all people were assigned to it.
